chore: Update time package to fix build
Building outside of the `nix develop` shell was failing:

```
error[E0282]: type annotations needed for `Box<_>`
  --> /home/<example_user>/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/time-0.3.20/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

Fixed by running:

```
$ cargo update time
```

Note I had to downgrade Cargo.lock back to v3 from v4 after the
update to avoid the following error which I figured is out of scope:
```
error: failed to parse lock file at: /example/path/to/github.com/superfly/corrosion/Cargo.lock
Caused by:
  lock file version 4 requires `-Znext-lockfile-bump`
  ```